st-parse-bbox: func(bbox: string) -> string
st-intersects: func(geom1: string, geom2: string) -> bool
st-contains: func(geom1: string, geom2: string) -> bool
st-clip-bbox: func(bbox: string, geom: string) -> string
